import { T, useI18n } from "@/lib/i18n";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ArrowUpRight, FileText, ShieldCheck, Pill, ArrowRightLeft, Check, Upload, ScanLine, FileCheck2, History, ChevronRight, HeartPulse } from "lucide-react";
import { Button } from "@/components/ui/button";
export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "MediScan — Medical information, made easier" }, { name: "description", content: "Understand your medical reports and medicine information. Explore findings, see the evidence, and prepare for your next doctor visit." }] }),
  component: Landing,
});

function Landing() {
  const { t } = useI18n();
  return (
    <div className="landing">
      <section className="home-container hero-grid">
        <div className="hero-copy">
          <p className="eyebrow"><span className="h-2 w-2 rounded-full bg-teal-600" /><T>A little clarity. A better conversation.</T></p>
          <h1><T>Medical information,</T><br /><span className="text-teal-700 dark:text-teal-300"><T>made easier</T></span><br /><T>to understand.</T></h1>
          <p className="hero-description"><T>Your health report shouldn't leave you with more questions. Understand what matters, see the evidence, and feel more prepared for your next doctor visit.</T></p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Button asChild size="lg" className="h-auto min-h-12 px-6"><Link to="/analyzer"><T>Analyze a Report</T><ArrowRight className="ml-2 h-4 w-4" /></Link></Button>
            <Button asChild size="lg" variant="outline" className="h-auto min-h-12 bg-card px-5"><Link to="/medicines"><Pill className="mr-2 h-4 w-4" /><T>Explore Medicine Lens</T></Link></Button>
          </div>
          <div className="mt-5 flex flex-wrap items-center gap-x-5 gap-y-3 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-teal-700" /><T>No account needed to start</T></span><Link to="/demo" className="inline-flex items-center gap-1 font-semibold text-foreground underline-offset-4 hover:underline"><T>Try a guided demo</T><ChevronRight className="h-3.5 w-3.5" /></Link></div>
        </div>
        <ReportPreview />
      </section>

      <section className="home-container pb-14 sm:pb-20" aria-labelledby="how-title">
        <div className="workflow-strip">
          <div className="workflow-intro"><p className="eyebrow"><T>Getting started</T></p><h2 id="how-title" className="mt-2 text-xl font-semibold"><T>Clarity in three steps.</T></h2></div>
          {[[Upload, "01", t("Upload"), t("Add your medical report.")], [FileText, "02", t("Understand"), t("See what needs a closer look.")], [ShieldCheck, "03", t("Verify"), t("Explore the evidence behind it.")]].map(([Icon, n, title, desc]) => { const StepIcon = Icon as typeof Upload; return <div className="workflow-step" key={String(n)}><span className="step-number">{String(n)}</span><div><h3 className="flex items-center gap-2 font-semibold"><StepIcon className="h-4 w-4 text-teal-700 dark:text-teal-300" /><T>{String(title)}</T></h3><p className="mt-1 text-sm text-muted-foreground"><T>{String(desc)}</T></p></div></div>; })}
        </div>
      </section>

      <section className="home-container section-space pt-0">
        <div className="section-heading"><div><p className="eyebrow"><T>One place. Three simple ways to start.</T></p><h2><T>What would you like to do?</T></h2></div><p><T>Choose what you need. We'll guide you from there.</T></p></div>
        <div className="grid gap-4 md:grid-cols-3">
          {[{ icon: FileText, title: t("Understand a report"), desc: t("Turn lab values into clear findings, with the reference range and evidence right beside them."), to: "/analyzer", cta: t("Analyze Report"), className: "entry-featured" }, { icon: Pill, title: t("Explore a medicine"), desc: t("Search a medicine or scan its packaging to explore ingredients and available references."), to: "/medicines", cta: t("Open Medicine Lens"), className: "" }, { icon: ArrowRightLeft, title: t("Check interactions"), desc: t("Look up combinations of medicines in our verified interaction reference set."), to: "/medicines", hash: "drug-interaction-checker", cta: t("Check Interactions"), className: "" }].map(({ icon: Icon, ...item }) => <Link key={item.title} to={item.to} hash={item.hash} className={`entry-card group ${item.className}`}><div className="entry-icon"><Icon className="h-6 w-6" /></div><h3><T>{item.title}</T></h3><p><T>{item.desc}</T></p><span className="mt-auto flex items-center justify-between pt-8 text-sm font-semibold"><T>{item.cta}</T><ArrowUpRight className="h-4 w-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></span></Link>)}
        </div>
      </section>

      <section className="evidence-section section-space">
        <div className="home-container grid items-center gap-10 lg:grid-cols-2 lg:gap-20">
          <div><p className="eyebrow"><ShieldCheck className="h-4 w-4" /><T>Understanding starts with evidence</T></p><h2 className="section-title mt-4"><T>More than an answer.</T><br /><T>See where it comes from.</T></h2><p className="mt-5 max-w-md leading-relaxed text-muted-foreground"><T>Every important finding has a story: a value in your report, a reference to compare it with, and evidence you can check for yourself.</T></p><Link to="/demo" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary"><T>See it in the demo</T><ArrowRight className="h-4 w-4" /></Link></div>
          <div className="evidence-path"><p className="mb-5 text-xs font-medium uppercase tracking-widest text-muted-foreground"><T>From your report to understanding</T></p>{[["01", t("Your report"), t("The original words and values.")], ["02", t("Value + reference range"), t("A comparison with your report's own range.")], ["03", t("Supporting evidence"), t("See why a finding was flagged.")], ["04", t("Verification ID"), t("A traceable record of the evidence checks.")]].map(([n,title,desc]) => <div className="evidence-path-row" key={n}><span>{n}</span><div><h3 className="font-semibold text-sm"><T>{title}</T></h3><p className="mt-1 text-sm text-muted-foreground"><T>{desc}</T></p></div>{n === "04" && <ShieldCheck className="ml-auto h-5 w-5 shrink-0 text-teal-700 dark:text-teal-300" />}</div>)}</div>
        </div>
      </section>

      <section className="home-container section-space">
        <div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-20">
          <div className="medicine-illustration"><div className="flex items-center justify-between border-b border-border pb-5"><span className="flex items-center gap-2 text-sm font-semibold"><ScanLine className="h-5 w-5 text-teal-700" /><T>Medicine Lens</T></span><span className="sample-label"><T>Illustrative preview</T></span></div><div className="package-frame"><div className="medicine-package"><span className="text-[10px] tracking-[0.2em] text-muted-foreground"><T>EXAMPLE PACKAGE</T></span><strong className="mt-4 block text-2xl tracking-tight">Paracetamol</strong><span className="mt-2 block text-sm text-muted-foreground">500 mg</span><Pill className="absolute bottom-5 right-5 h-10 w-10 text-teal-700/60" /></div></div><div className="flex items-center gap-3 rounded-xl border border-border bg-background p-4"><ShieldCheck className="h-6 w-6 shrink-0 text-teal-700 dark:text-teal-300" /><div><p className="text-sm font-semibold"><T>Package → Ingredient → Reference</T></p><p className="mt-1 text-xs text-muted-foreground"><T>Original names and strengths stay unchanged.</T></p></div></div></div>
          <div><p className="eyebrow"><Pill className="h-4 w-4" /><T>A clearer look at your medicines</T></p><h2 className="section-title mt-4"><T>From the package</T><br /><T>to the information.</T></h2><p className="mt-5 leading-relaxed text-muted-foreground"><T>Medicine names can be confusing. Search by name or upload a clear packaging photo to explore ingredients, strengths, and source information.</T></p><ul className="mt-6 space-y-3 text-sm">{[t("Search familiar brand or ingredient names"), t("Read information from the available reference set"), t("Know when a medicine cannot be verified")].map(text => <li key={text} className="flex items-start gap-2.5"><Check className="mt-0.5 h-4 w-4 shrink-0 text-teal-700 dark:text-teal-300" /><T>{text}</T></li>)}</ul><Button asChild variant="outline" className="mt-7 h-auto min-h-11"><Link to="/medicines"><T>Explore Medicine Lens</T><ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div>
        </div>
        <div className="mt-20 grid gap-7 border-t border-border pt-9 sm:grid-cols-3">{[[FileCheck2, t("Ready for your next visit"), t("Bring a concise Doctor Visit Brief to your next appointment.")], [HeartPulse, t("A simpler health summary"), t("Review the findings in an easier-to-read Patient Health Summary.")], [History, t("Pick up where you left off"), t("Sign in to keep your reports and medicine scans in your history.")]].map(([Icon,title,desc]) => { const FeatureIcon = Icon as typeof History; return <div key={String(title)}><FeatureIcon className="mb-4 h-5 w-5 text-teal-700 dark:text-teal-300" /><h3 className="font-semibold"><T>{String(title)}</T></h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground"><T>{String(desc)}</T></p></div>; })}</div>
      </section>

      <section className="home-container pb-16"><div className="trust-note"><ShieldCheck className="h-7 w-7 shrink-0 text-teal-700 dark:text-teal-300" /><div><h2 className="font-semibold"><T>Made to support your conversations with healthcare professionals.</T></h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground"><T>MediScan is an educational and decision-support tool. It does not diagnose conditions, prescribe treatment, or replace professional medical advice.</T></p><Link to="/about" hash="privacy" className="mt-3 inline-block text-xs font-semibold text-primary underline underline-offset-4"><T>About privacy and your data</T></Link></div></div></section>
      <section className="closing-section"><div className="home-container flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><div><p className="eyebrow text-teal-200"><T>A clearer next step</T></p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl"><T>Start understanding your reports.</T></h2><p className="mt-3 text-slate-300"><T>Take the first step, at your own pace.</T></p></div><div className="flex flex-wrap gap-3"><Button asChild size="lg" className="h-auto min-h-12 bg-white text-slate-900 hover:bg-slate-100"><Link to="/analyzer"><T>Analyze a Report</T><ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild size="lg" variant="ghost" className="h-auto min-h-12 text-white hover:bg-white/10 hover:text-white"><Link to="/medicines"><T>Explore Medicine Lens</T><ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div></div></section>
    </div>
  );
}

function ReportPreview() {
  return <div className="report-preview-wrap"><div className="preview-orbit" aria-hidden="true" /><div className="report-preview"><div className="preview-topbar"><span className="flex items-center gap-2"><span className="flex gap-1.5" aria-hidden="true"><i /><i /><i /></span><span className="ml-2 text-xs text-muted-foreground">MediScan</span></span><span className="sample-label"><T>Illustrative preview</T></span></div><div className="p-5 sm:p-7"><div className="mb-6 flex items-center gap-3"><div className="rounded-xl bg-teal-50 p-3 text-teal-700 dark:bg-teal-950"><FileText className="h-5 w-5" /></div><div><h2 className="font-semibold"><T>Blood Test Report</T></h2><p className="mt-1 text-xs text-muted-foreground"><T>A simpler view of your findings</T></p></div></div><div className="rounded-xl border border-border p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm font-semibold">Hemoglobin</span><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[11px] font-medium text-amber-800 dark:bg-amber-950 dark:text-amber-200"><T>Below reference range</T></span></div><div className="mt-5 flex flex-wrap items-end justify-between gap-3"><p className="text-3xl font-semibold tracking-tight">11.2 <span className="text-sm font-normal text-muted-foreground">g/dL</span></p><p className="text-xs text-muted-foreground"><T>Reference range</T><br /><strong className="mt-1 inline-block font-medium text-foreground">12–16 g/dL</strong></p></div><div className="preview-range mt-5" aria-hidden="true"><span /></div><p className="mt-4 text-xs leading-relaxed text-muted-foreground"><T>This value is below the reference range shown in this example report. Discuss it with your healthcare professional.</T></p></div><div className="mt-4 flex items-center gap-2 rounded-lg bg-teal-50 px-3 py-3 text-xs text-teal-800 dark:bg-teal-950 dark:text-teal-200"><ShieldCheck className="h-4 w-4 shrink-0" /><T>Evidence checks connect findings to the source.</T></div><Link to="/demo" className="mt-5 flex items-center justify-between text-xs font-semibold text-primary"><T>Explore a working sample</T><ArrowRight className="h-4 w-4" /></Link></div></div><div className="preview-brief"><span className="rounded-lg bg-teal-50 p-2.5 text-teal-700 dark:bg-teal-950"><FileCheck2 className="h-5 w-5" /></span><div><p className="text-sm font-semibold"><T>Your next doctor visit, made easier.</T></p><p className="mt-1 text-xs text-muted-foreground"><T>Clear findings. Useful questions.</T></p></div><Check className="ml-auto h-4 w-4 shrink-0 text-teal-700 dark:text-teal-300" /></div></div>;
}
